<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260925120257 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Orders, order history and the Messenger queue table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE shop_order (id UUID NOT NULL, status VARCHAR(32) NOT NULL, erp_reference VARCHAR(64) DEFAULT NULL, export_attempts INT NOT NULL, last_error TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, source VARCHAR(32) NOT NULL, external_id VARCHAR(64) NOT NULL, customer_email VARCHAR(180) NOT NULL, customer_name VARCHAR(180) NOT NULL, currency VARCHAR(3) NOT NULL, total_gross INT NOT NULL, lines JSON NOT NULL, payload_hash VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_order_status ON shop_order (status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_order_source_external_id ON shop_order (source, external_id)');
        $this->addSql('CREATE TABLE shop_order_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(32) NOT NULL, message TEXT DEFAULT NULL, order_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6A47884A8D9F6D38 ON shop_order_event (order_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE shop_order_event ADD CONSTRAINT FK_6A47884A8D9F6D38 FOREIGN KEY (order_id) REFERENCES shop_order (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE shop_order_event DROP CONSTRAINT FK_6A47884A8D9F6D38');
        $this->addSql('DROP TABLE shop_order');
        $this->addSql('DROP TABLE shop_order_event');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
